services:
  db:
    image: postgres:latest
    container_name: persons-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: persons_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: