spring.application.name=hibernate

spring.datasource.url=jdbc:postgresql://localhost:5434/persons_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.change-log=db.changelog/db.changelog-master.yaml